#!/bin/sh

# Welcome to the chromebook script!
# Be prepared to turn your chromebook
# into an awesome development machine.

sh functions

sh ubuntu-node-stack

fancy_echo 'node installed at version:'
node -v
