#!/bin/sh

# Welcome to the chromebook script!
# Be prepared to turn your chromebook
# into an awesome development machine.

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

fancy_echo 'testing'
